package com.deepwares.fishmarketplace.model

import com.deepwares.fishmarketplace.R
import com.deepwares.fishmarketplace.model.Species

object FishRepository {
    val species = arrayListOf(

        Species(
            R.string.anchovy,
            R.drawable.anchovy,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        Species(
            R.string.bombay_duck,
            R.drawable.bombay_duck,
            R.integer.bombay_duck_status,
            R.integer.bombay_duck_min_price,
            R.integer.bombay_duck_max_price,
            R.string.bombay_duck_scientific_name,
            R.string.bombay_duck_common_name,
            R.string.bombay_duck_description
        ),
        Species(
            R.string.giant_sea_perch,
            R.drawable.baramundi,
            R.integer.giant_sea_perch_status,
            R.integer.giant_sea_perch_min_price,
            R.integer.giant_sea_perch_max_price,
            R.string.giant_sea_perch_scientific_name,
            R.string.giant_sea_perch_common_name,
            R.string.giant_sea_perch_description
        ),
        Species(
            R.string.river_sole,
            R.drawable.sole,
            R.integer.river_sole_status,
            R.integer.river_sole_min_price,
            R.integer.river_sole_max_price,
            R.string.river_sole_scientific_name,
            R.string.river_sole_common_name,
            R.string.river_sole_description
        ),
        Species(
            R.string.sea_sole,
            R.drawable.sole,
            R.integer.sea_sole_status,
            R.integer.sea_sole_min_price,
            R.integer.sea_sole_max_price,
            R.string.sea_sole_scientific_name,
            R.string.sea_sole_common_name,
            R.string.sea_sole_description
        ),
        Species(
            R.string.pomfret,
            R.drawable.pomfret,
            R.integer.pomfret_status,
            R.integer.pomfret_min_price,
            R.integer.pomfret_max_price,
            R.string.pomfret_scientific_name,
            R.string.black_pomfret_common_name,
            R.string.pomfret_description
        ),
        Species(
            R.string.salmon,
            R.drawable.salmon,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        Species(
            R.string.kingfish,
            R.drawable.kingfish,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        Species(
            R.string.red_snapper,
            R.drawable.red_snapper,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        Species(
            R.string.grouper,
            R.drawable.grouper,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        Species(
            R.string.tuna,
            R.drawable.tuna,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        Species(
            R.string.peral_spot,
            R.drawable.pearl_spot,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        /* Species(
             R.string.ladyfish,
             R.drawable.ladyfish,
             R.integer.anchovy_status,
             R.integer.anchovy_min_price,
             R.integer.anchovy_max_price,
             R.string.anchovy_scientific_name,
             R.string.anchovy_common_name,
             R.string.anchovy_description
         ),
         Species(
             R.string.hilsa,
             R.drawable.hilsa,
             R.integer.anchovy_status,
             R.integer.anchovy_min_price,
             R.integer.anchovy_max_price,
             R.string.anchovy_scientific_name,
             R.string.anchovy_common_name,
             R.string.anchovy_description
         ),
         Species(
             R.string.mackerel,
             R.drawable.mackerel,
             R.integer.anchovy_status,
             R.integer.anchovy_min_price,
             R.integer.anchovy_max_price,
             R.string.anchovy_scientific_name,
             R.string.anchovy_common_name,
             R.string.anchovy_description
         ),*/
        Species(
            R.string.black_pomfret,
            R.drawable.pomfret,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        Species(
            R.string.mullet,
            R.drawable.mullet,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        /*Species(
            R.string.sardine,
            R.drawable.sardine,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        Species(
            R.string.croaker,
            R.drawable.croaker,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        Species(
            R.string.shark,
            R.drawable.shark,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        Species(
            R.string.ray,
            R.drawable.ray,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),*/
        Species(
            R.string.ghole,
            R.drawable.ghole,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        /* Species(
             R.string.murrel,
             R.drawable.murrel,
             R.integer.anchovy_status,
             R.integer.anchovy_min_price,
             R.integer.anchovy_max_price,
             R.string.anchovy_scientific_name,
             R.string.anchovy_common_name,
             R.string.anchovy_description
         ),*/
        Species(
            R.string.seerfish,
            R.drawable.seer,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        Species(
            R.string.sea_veral,
            R.drawable.sea_veral,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),

        /* Species(
             R.string.squid,
             R.drawable.squid,
             R.integer.anchovy_status,
             R.integer.anchovy_min_price,
             R.integer.anchovy_max_price,
             R.string.anchovy_scientific_name,
             R.string.anchovy_common_name,
             R.string.anchovy_description
         ),*/
        Species(
            R.string.tiger_prawn,
            R.drawable.tiger_prawn,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        Species(
            R.string.prawns,
            R.drawable.prawns,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        Species(
            R.string.shrimp,
            R.drawable.shrimp,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        ),
        /* Species(
             R.string.lobster,
             R.drawable.lobster,
             R.integer.anchovy_status,
             R.integer.anchovy_min_price,
             R.integer.anchovy_max_price,
             R.string.anchovy_scientific_name,
             R.string.anchovy_common_name,
             R.string.anchovy_description
         ),
         Species(
             R.string.crab,
             R.drawable.crab,
             R.integer.anchovy_status,
             R.integer.anchovy_min_price,
             R.integer.anchovy_max_price,
             R.string.anchovy_scientific_name,
             R.string.anchovy_common_name,
             R.string.anchovy_description
         ),
         Species(
             R.string.short_necked_clams,
             R.drawable.short_necked_clams,
             R.integer.anchovy_status,
             R.integer.anchovy_min_price,
             R.integer.anchovy_max_price,
             R.string.anchovy_scientific_name,
             R.string.anchovy_common_name,
             R.string.anchovy_description
         ),*/
        /* Species(
             R.string.mussels,
             R.drawable.mussels,
             R.integer.anchovy_status,
             R.integer.anchovy_min_price,
             R.integer.anchovy_max_price,
             R.string.anchovy_scientific_name,
             R.string.anchovy_common_name,
             R.string.anchovy_description
         ),*/
        Species(
            R.string.mahi_mahi,
            R.drawable.mahi_mahi,
            R.integer.anchovy_status,
            R.integer.anchovy_min_price,
            R.integer.anchovy_max_price,
            R.string.anchovy_scientific_name,
            R.string.anchovy_common_name,
            R.string.anchovy_description
        )
        /* ,
         Species(
             R.string.coconut_para,
             R.drawable.coconut_para,
             R.integer.anchovy_status,
             R.integer.anchovy_min_price,
             R.integer.anchovy_max_price,
             R.string.anchovy_scientific_name,
             R.string.anchovy_common_name,
             R.string.anchovy_description
         ),*/
    )
}